### ISSUE TITLE
doesn't work with kernel 4.14.0

### ISSUE THREAD

**Issue by a2nt** [ulli-kroll/rtl8821au#16]
```
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.14.0-kali1-amd64/build M=/home/tony/Drivers/ulli-kroll-rtl8821au  modules
make[1]: Entering directory '/usr/src/linux-headers-4.14.0-kali1-amd64'
  CC [M]  /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.o
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:32:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/osdep_service.h: In function ‘thread_enter’:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/osdep_service.h:100:2: error: implicit declaration of function ‘allow_signal’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
  do_signal
/home/tony/Drivers/ulli-kroll-rtl8821au/include/osdep_service.h: In function ‘flush_signals_thread’:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/osdep_service.h:105:6: error: implicit declaration of function ‘signal_pending’; did you mean ‘timer_pending’? [-Werror=implicit-function-declaration]
  if (signal_pending (current)) {
      ^~~~~~~~~~~~~~
      timer_pending
/home/tony/Drivers/ulli-kroll-rtl8821au/include/osdep_service.h:106:3: error: implicit declaration of function ‘flush_signals’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
   do_signal
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:5:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:34,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/usb.h: At top level:
/home/tony/Drivers/ulli-kroll-rtl8821au/usb.h:92:12: error: ‘NUM_STA’ undeclared here (not in a function); did you mean ‘NUD_STALE’?
  int macid[NUM_STA];
            ^~~~~~~
            NUD_STALE
/home/tony/Drivers/ulli-kroll-rtl8821au/usb.h:143:21: error: field ‘ledpriv’ has incomplete type
  struct rtl_led_ctl ledpriv;
                     ^~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/usb.h:161:77: warning: ‘struct xmit_buf’ declared inside parameter list will not be visible outside of this definition or declaration
 lw_usb_transmit(struct rtl_priv *rtlpriv, u32 addr, u32 cnt, struct xmit_buf *pxmitbu);
                                                                     ^~~~~~~~
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:34:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1509:20: error: ‘P2P_MAX_NOA_NUM’ undeclared here (not in a function); did you mean ‘RF_MAX_TX_NUM’?
  u8 noa_count_type[P2P_MAX_NOA_NUM];
                    ^~~~~~~~~~~~~~~
                    RF_MAX_TX_NUM
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1662:31: error: ‘PSBBREG_TOTALCNT’ undeclared here (not in a function)
  unsigned long PS_BBRegBackup[PSBBREG_TOTALCNT];
                               ^~~~~~~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1764:19: error: field ‘mlmepriv’ has incomplete type
  struct mlme_priv mlmepriv;
                   ^~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1765:23: error: field ‘mlmeextpriv’ has incomplete type
  struct mlme_ext_priv mlmeextpriv;
                       ^~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1766:18: error: field ‘cmdpriv’ has incomplete type
  struct cmd_priv cmdpriv;
                  ^~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1767:18: error: field ‘evtpriv’ has incomplete type
  struct evt_priv evtpriv;
                  ^~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1769:19: error: field ‘xmitpriv’ has incomplete type
  struct xmit_priv xmitpriv;
                   ^~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1770:19: error: field ‘recvpriv’ has incomplete type
  struct recv_priv recvpriv;
                   ^~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1771:18: error: field ‘stapriv’ has incomplete type
  struct sta_priv stapriv;
                  ^~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1772:23: error: field ‘securitypriv’ has incomplete type
  struct security_priv securitypriv;
                       ^~~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1773:23: error: field ‘registrypriv’ has incomplete type
  struct registry_priv registrypriv;
                       ^~~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1801:23: error: field ‘iwstats’ has incomplete type
  struct iw_statistics iwstats;
                       ^~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1922:54: warning: ‘enum led_ctl_mode’ declared inside parameter list will not be visible outside of this definition or declaration
  void (*led_control) (struct rtl_priv *rtlpriv, enum led_ctl_mode ledcation);
                                                      ^~~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1974:60: warning: ‘enum CHANNEL_WIDTH’ declared inside parameter list will not be visible outside of this definition or declaration
  void (*set_bwmode_handler)(struct rtl_priv *rtlpriv, enum CHANNEL_WIDTH Bandwidth, uint8_t Offset);
                                                            ^~~~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1976:78: warning: ‘enum CHANNEL_WIDTH’ declared inside parameter list will not be visible outside of this definition or declaration
 et_chnl_bw_handler)(struct rtl_priv *rtlpriv, uint8_t channel, enum CHANNEL_WIDTH Bandwidth, uint8_t Offset40, uint8_t Offset80);
                                                                     ^~~~~~~~~~~~~
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:34:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1982:55: warning: ‘struct xmit_frame’ declared inside parameter list will not be visible outside of this definition or declaration
  int32_t (*hal_xmit)(struct rtl_priv *rtlpriv, struct xmit_frame *pxmitframe);
                                                       ^~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1983:56: warning: ‘struct xmit_frame’ declared inside parameter list will not be visible outside of this definition or declaration
  int32_t (*mgnt_xmit)(struct rtl_priv *rtlpriv, struct xmit_frame *pmgntframe);
                                                        ^~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1984:68: warning: ‘struct xmit_frame’ declared inside parameter list will not be visible outside of this definition or declaration
  int32_t (*hal_xmitframe_enqueue)(struct rtl_priv *rtlpriv, struct xmit_frame *pxmitframe);
                                                                    ^~~~~~~~~~
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:35:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/ieee80211.h:258:32: error: field ‘ht_cap’ has incomplete type
    struct rtw_ieee80211_ht_cap ht_cap;
                                ^~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/ieee80211.h:283:30: error: field ‘ht_cap’ has incomplete type
  struct rtw_ieee80211_ht_cap ht_cap;
                              ^~~~~~
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:24:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:48,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_ht.h:46:30: error: field ‘ht_cap’ has incomplete type
  struct rtw_ieee80211_ht_cap ht_cap;
                              ^~~~~~
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:48:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:169:16: error: ‘WLAN_SSID_MAXLEN’ undeclared here (not in a function); did you mean ‘WLAN_BSSID_EX’?
  uint8_t ssid[ WLAN_SSID_MAXLEN ];
                ^~~~~~~~~~~~~~~~
                WLAN_BSSID_EX
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:48:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:232:37: error: ‘P2P_MAX_PERSISTENT_GROUP_NUM’ undeclared here (not in a function); did you mean ‘P2P_MAX_NOA_NUM’?
  struct profile_info   profileinfo[ P2P_MAX_PERSISTENT_GROUP_NUM ]; // Store the profile information of persistent group
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                     P2P_MAX_NOA_NUM
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:238:18: error: field ‘role’ has incomplete type
  enum P2P_ROLE   role;
                  ^~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:239:19: error: field ‘pre_p2p_state’ has incomplete type
  enum P2P_STATE   pre_p2p_state;
                   ^~~~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:240:19: error: field ‘p2p_state’ has incomplete type
  enum P2P_STATE   p2p_state;
                   ^~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:248:33: error: ‘P2P_WILDCARD_SSID_LEN’ undeclared here (not in a function)
  uint8_t      p2p_wildcard_ssid[P2P_WILDCARD_SSID_LEN];
                                 ^~~~~~~~~~~~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:253:28: error: ‘WPS_MAX_DEVICE_NAME_LEN’ undeclared here (not in a function); did you mean ‘APM_DEVICE_PARALLEL’?
  uint8_t      device_name[ WPS_MAX_DEVICE_NAME_LEN ]; // Device name for displaying on searching device screen
                            ^~~~~~~~~~~~~~~~~~~~~~~
                            APM_DEVICE_PARALLEL
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:283:20: error: field ‘ui_got_wps_info’ has incomplete type
  enum P2P_WPSINFO  ui_got_wps_info;   // This field will store the WPS value (PIN value or PBC) that UI had got from the user.
                    ^~~~~~~~~~~~~~~
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:56:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme_ext.h:374:24: error: field ‘ADDBA_req’ has incomplete type
  struct ADDBA_request  ADDBA_req;
                        ^~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme_ext.h:375:26: error: field ‘WMM_param’ has incomplete type
  struct WMM_para_element WMM_param;
                          ^~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme_ext.h:376:25: error: field ‘HT_caps’ has incomplete type
  struct HT_caps_element HT_caps;
                         ^~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme_ext.h:377:26: error: field ‘HT_info’ has incomplete type
  struct HT_info_element  HT_info;
                          ^~~~~~~
cc1: some warnings being treated as errors
/usr/src/linux-headers-4.14.0-kali1-common/scripts/Makefile.build:319: recipe for target '/home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.o' failed
make[4]: *** [/home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.o] Error 1
/usr/src/linux-headers-4.14.0-kali1-common/Makefile:1520: recipe for target '_module_/home/tony/Drivers/ulli-kroll-rtl8821au' failed
make[3]: *** [_module_/home/tony/Drivers/ulli-kroll-rtl8821au] Error 2
Makefile:146: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.14.0-kali1-amd64'
Makefile:116: recipe for target 'modules' failed
make: *** [modules] Error 2
➜  ulli-kroll-rtl8821au git:(master) make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.14.0-kali1-amd64/build M=/home/tony/Drivers/ulli-kroll-rtl8821au  modules
make[1]: Entering directory '/usr/src/linux-headers-4.14.0-kali1-amd64'
  CC [M]  /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.o
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:32:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/osdep_service.h: In function ‘thread_enter’:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/osdep_service.h:100:2: error: implicit declaration of function ‘allow_signal’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
  do_signal
/home/tony/Drivers/ulli-kroll-rtl8821au/include/osdep_service.h: In function ‘flush_signals_thread’:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/osdep_service.h:105:6: error: implicit declaration of function ‘signal_pending’; did you mean ‘timer_pending’? [-Werror=implicit-function-declaration]
  if (signal_pending (current)) {
      ^~~~~~~~~~~~~~
      timer_pending
/home/tony/Drivers/ulli-kroll-rtl8821au/include/osdep_service.h:106:3: error: implicit declaration of function ‘flush_signals’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
   do_signal
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:5:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:34,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/usb.h: At top level:
/home/tony/Drivers/ulli-kroll-rtl8821au/usb.h:92:12: error: ‘NUM_STA’ undeclared here (not in a function); did you mean ‘NUD_STALE’?
  int macid[NUM_STA];
            ^~~~~~~
            NUD_STALE
/home/tony/Drivers/ulli-kroll-rtl8821au/usb.h:143:21: error: field ‘ledpriv’ has incomplete type
  struct rtl_led_ctl ledpriv;
                     ^~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/usb.h:161:77: warning: ‘struct xmit_buf’ declared inside parameter list will not be visible outside of this definition or declaration
 lw_usb_transmit(struct rtl_priv *rtlpriv, u32 addr, u32 cnt, struct xmit_buf *pxmitbu);
                                                                     ^~~~~~~~
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:34:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1509:20: error: ‘P2P_MAX_NOA_NUM’ undeclared here (not in a function); did you mean ‘RF_MAX_TX_NUM’?
  u8 noa_count_type[P2P_MAX_NOA_NUM];
                    ^~~~~~~~~~~~~~~
                    RF_MAX_TX_NUM
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1662:31: error: ‘PSBBREG_TOTALCNT’ undeclared here (not in a function)
  unsigned long PS_BBRegBackup[PSBBREG_TOTALCNT];
                               ^~~~~~~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1764:19: error: field ‘mlmepriv’ has incomplete type
  struct mlme_priv mlmepriv;
                   ^~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1765:23: error: field ‘mlmeextpriv’ has incomplete type
  struct mlme_ext_priv mlmeextpriv;
                       ^~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1766:18: error: field ‘cmdpriv’ has incomplete type
  struct cmd_priv cmdpriv;
                  ^~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1767:18: error: field ‘evtpriv’ has incomplete type
  struct evt_priv evtpriv;
                  ^~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1769:19: error: field ‘xmitpriv’ has incomplete type
  struct xmit_priv xmitpriv;
                   ^~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1770:19: error: field ‘recvpriv’ has incomplete type
  struct recv_priv recvpriv;
                   ^~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1771:18: error: field ‘stapriv’ has incomplete type
  struct sta_priv stapriv;
                  ^~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1772:23: error: field ‘securitypriv’ has incomplete type
  struct security_priv securitypriv;
                       ^~~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1773:23: error: field ‘registrypriv’ has incomplete type
  struct registry_priv registrypriv;
                       ^~~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1801:23: error: field ‘iwstats’ has incomplete type
  struct iw_statistics iwstats;
                       ^~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1922:54: warning: ‘enum led_ctl_mode’ declared inside parameter list will not be visible outside of this definition or declaration
  void (*led_control) (struct rtl_priv *rtlpriv, enum led_ctl_mode ledcation);
                                                      ^~~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1974:60: warning: ‘enum CHANNEL_WIDTH’ declared inside parameter list will not be visible outside of this definition or declaration
  void (*set_bwmode_handler)(struct rtl_priv *rtlpriv, enum CHANNEL_WIDTH Bandwidth, uint8_t Offset);
                                                            ^~~~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1976:78: warning: ‘enum CHANNEL_WIDTH’ declared inside parameter list will not be visible outside of this definition or declaration
 et_chnl_bw_handler)(struct rtl_priv *rtlpriv, uint8_t channel, enum CHANNEL_WIDTH Bandwidth, uint8_t Offset40, uint8_t Offset80);
                                                                     ^~~~~~~~~~~~~
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:34:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1982:55: warning: ‘struct xmit_frame’ declared inside parameter list will not be visible outside of this definition or declaration
  int32_t (*hal_xmit)(struct rtl_priv *rtlpriv, struct xmit_frame *pxmitframe);
                                                       ^~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1983:56: warning: ‘struct xmit_frame’ declared inside parameter list will not be visible outside of this definition or declaration
  int32_t (*mgnt_xmit)(struct rtl_priv *rtlpriv, struct xmit_frame *pmgntframe);
                                                        ^~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/wifi.h:1984:68: warning: ‘struct xmit_frame’ declared inside parameter list will not be visible outside of this definition or declaration
  int32_t (*hal_xmitframe_enqueue)(struct rtl_priv *rtlpriv, struct xmit_frame *pxmitframe);
                                                                    ^~~~~~~~~~
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:35:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/ieee80211.h:258:32: error: field ‘ht_cap’ has incomplete type
    struct rtw_ieee80211_ht_cap ht_cap;
                                ^~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/ieee80211.h:283:30: error: field ‘ht_cap’ has incomplete type
  struct rtw_ieee80211_ht_cap ht_cap;
                              ^~~~~~
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:24:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:48,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_ht.h:46:30: error: field ‘ht_cap’ has incomplete type
  struct rtw_ieee80211_ht_cap ht_cap;
                              ^~~~~~
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:48:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:169:16: error: ‘WLAN_SSID_MAXLEN’ undeclared here (not in a function); did you mean ‘WLAN_BSSID_EX’?
  uint8_t ssid[ WLAN_SSID_MAXLEN ];
                ^~~~~~~~~~~~~~~~
                WLAN_BSSID_EX
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:48:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:232:37: error: ‘P2P_MAX_PERSISTENT_GROUP_NUM’ undeclared here (not in a function); did you mean ‘P2P_MAX_NOA_NUM’?
  struct profile_info   profileinfo[ P2P_MAX_PERSISTENT_GROUP_NUM ]; // Store the profile information of persistent group
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                     P2P_MAX_NOA_NUM
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:238:18: error: field ‘role’ has incomplete type
  enum P2P_ROLE   role;
                  ^~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:239:19: error: field ‘pre_p2p_state’ has incomplete type
  enum P2P_STATE   pre_p2p_state;
                   ^~~~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:240:19: error: field ‘p2p_state’ has incomplete type
  enum P2P_STATE   p2p_state;
                   ^~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:248:33: error: ‘P2P_WILDCARD_SSID_LEN’ undeclared here (not in a function)
  uint8_t      p2p_wildcard_ssid[P2P_WILDCARD_SSID_LEN];
                                 ^~~~~~~~~~~~~~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:253:28: error: ‘WPS_MAX_DEVICE_NAME_LEN’ undeclared here (not in a function); did you mean ‘APM_DEVICE_PARALLEL’?
  uint8_t      device_name[ WPS_MAX_DEVICE_NAME_LEN ]; // Device name for displaying on searching device screen
                            ^~~~~~~~~~~~~~~~~~~~~~~
                            APM_DEVICE_PARALLEL
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme.h:283:20: error: field ‘ui_got_wps_info’ has incomplete type
  enum P2P_WPSINFO  ui_got_wps_info;   // This field will store the WPS value (PIN value or PBC) that UI had got from the user.
                    ^~~~~~~~~~~~~~~
In file included from /home/tony/Drivers/ulli-kroll-rtl8821au/include/drv_types.h:56:0,
                 from /home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.c:25:
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme_ext.h:374:24: error: field ‘ADDBA_req’ has incomplete type
  struct ADDBA_request  ADDBA_req;
                        ^~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme_ext.h:375:26: error: field ‘WMM_param’ has incomplete type
  struct WMM_para_element WMM_param;
                          ^~~~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme_ext.h:376:25: error: field ‘HT_caps’ has incomplete type
  struct HT_caps_element HT_caps;
                         ^~~~~~~
/home/tony/Drivers/ulli-kroll-rtl8821au/include/rtw_mlme_ext.h:377:26: error: field ‘HT_info’ has incomplete type
  struct HT_info_element  HT_info;
                          ^~~~~~~
cc1: some warnings being treated as errors
/usr/src/linux-headers-4.14.0-kali1-common/scripts/Makefile.build:319: recipe for target '/home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.o' failed
make[4]: *** [/home/tony/Drivers/ulli-kroll-rtl8821au/os_dep/osdep_service.o] Error 1
/usr/src/linux-headers-4.14.0-kali1-common/Makefile:1520: recipe for target '_module_/home/tony/Drivers/ulli-kroll-rtl8821au' failed
make[3]: *** [_module_/home/tony/Drivers/ulli-kroll-rtl8821au] Error 2
Makefile:146: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.14.0-kali1-amd64'
Makefile:116: recipe for target 'modules' failed
make: *** [modules] Error 2

```

**Comment by ulli-kroll** [comment]
Please check if your kernel sources are installed
and not the kernel header ..
